name: Find tasks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  check_tests_exist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install git+https://github.com/METR/vivaria.git#subdirectory=task-standard/python-package

    - name: Collect tasks
      run: |
        python -m pytest --ignore=assets --collect-only --quiet --task-standard-tasks-report=collected-tests.json

    - name: Check for tests
      run: |
        TEST_COUNT=$(cat collected-tests.json | jq '. | length')
        if [ "$TEST_COUNT" -eq 0 ]; then
          echo "No tasks found - please add `@pytest.mark.task_standard_tasks` to at least one test"
          exit 1
        fi
        echo "Found $TEST_COUNT tests"
