name: Initialize Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  initialize:
    if: github.run_number == 1
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Replace placeholders and rename files
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        echo "Repository name: $REPO_NAME"

        FILES=(
          "meta/eval_info.json"
          "task_family_name.py"
          "task_family_name_test.py"
          "DEVELOPER_GUIDE.md"
        )

        for filename in "${FILES[@]}"; do
          if [ -f "$filename" ]; then
            echo "Processing $filename"
            sed -i "s/task_family_name/$REPO_NAME/g" "$filename"
          else
            echo "File not found: $filename"
          fi
        done

        if [ -f "task_family_name.py" ]; then
          git mv task_family_name.py "${REPO_NAME}.py"
        fi
        if [ -f "task_family_name_test.py" ]; then
          git mv task_family_name_test.py "${REPO_NAME}_test.py"
        fi

    - name: Commit changes
      run: |
        git add .
        git commit -m "Initialize repository with correct naming" || echo "No changes to commit"
        git push
