name: Test Task

on:
  workflow_dispatch:
    inputs:
      task_name:
        description: 'Task Name'
        required: true
        type: string
  workflow_call:
    inputs:
      task_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}

    - name: Checkout task standard repository
      uses: actions/checkout@v3
      with:
        repository: METR/task-standard
        path: task-standard

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd task-standard/drivers
        npm install
        cd ../workbench
        npm install

    - name: Run test
      id: run_test
      run: |
        cd task-standard/workbench
        repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        result=$(npm run test ../../$repo_name ${{ inputs.task_name }} .)
        echo "$result"
        echo "result<<EOF" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        if ! echo "$result" | grep -qE " === (Starting|Running) tests ===|=== Tests finished ===" ||
           echo "$result" | grep -qE "ERROR|FAILED"; then
          exit 1
        fi
        if echo "$result" | grep -qE "ERROR|FAILED"; then
          echo "Test failed. Found ERROR or FAILED in the output."
          exit 1
        fi
